//! Port of blender_pipeline_executor.py — headless `blender -b -P` execution
//! with process-group management and timeout cleanup.

use serde_json::json;
use std::path::Path;

use crate::common::cli::{self, ArgSpec};
use crate::common::jsonfmt;
use crate::common::proc;
use crate::common::py;

pub fn find_blender_binary() -> Option<String> {
    // shutil.which("blender")
    if let Ok(path) = std::env::var("PATH") {
        for dir in std::env::split_paths(&path) {
            let cand = dir.join("blender");
            if cand.exists() && is_executable(&cand) {
                return Some(cand.to_string_lossy().into_owned());
            }
            #[cfg(windows)]
            {
                let cand = dir.join("blender.exe");
                if cand.exists() {
                    return Some(cand.to_string_lossy().into_owned());
                }
            }
        }
    }
    for p in [
        "/usr/bin/blender",
        "/usr/local/bin/blender",
        "/opt/blender/blender",
        "/snap/bin/blender",
    ] {
        let pp = Path::new(p);
        if pp.exists() && is_executable(pp) {
            return Some(p.to_string());
        }
    }
    let mac = "/Applications/Blender.app/Contents/MacOS/Blender";
    if Path::new(mac).exists() {
        return Some(mac.to_string());
    }
    for p in [
        r"C:\Program Files\Blender Foundation\Blender 4.2\blender.exe",
        r"C:\Program Files\Blender Foundation\Blender 4.1\blender.exe",
        r"C:\Program Files\Blender Foundation\Blender 4.0\blender.exe",
        r"C:\Program Files\Blender Foundation\Blender 3.6\blender.exe",
    ] {
        if Path::new(p).exists() {
            return Some(p.to_string());
        }
    }
    None
}

#[cfg(unix)]
fn is_executable(p: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    p.metadata()
        .map(|m| m.permissions().mode() & 0o111 != 0)
        .unwrap_or(false)
}

#[cfg(not(unix))]
fn is_executable(p: &Path) -> bool {
    p.exists()
}

pub fn execute_headless_blender_script(
    script_path: &str,
    extra_args: &[String],
    timeout_sec: u64,
) -> serde_json::Value {
    let blender = match find_blender_binary() {
        Some(b) => b,
        None => {
            return json!({
                "status": "UNAVAILABLE",
                "error": "Blender executable not found on system. Generated scripts can still be run on client workstation.",
                "command": format!("blender -b -P {}", script_path)
            });
        }
    };
    let mut cmd = vec![
        blender,
        "-b".to_string(),
        "--python".to_string(),
        script_path.to_string(),
    ];
    if !extra_args.is_empty() {
        cmd.push("--".to_string());
        cmd.extend(extra_args.iter().cloned());
    }
    println!(
        "[Blender Runner] Executing in new process group: {}",
        cmd.join(" ")
    );

    match proc::run_capture(&cmd, timeout_sec) {
        Ok(out) if out.timed_out => json!({
            "status": "TIMEOUT",
            "error": format!("Blender pipeline timed out after {} seconds and was cleanly terminated.", timeout_sec)
        }),
        Ok(out) => {
            let code = out.status.and_then(|s| s.code()).unwrap_or(-1);
            json!({
                "status": if code == 0 { "SUCCESS" } else { "ERROR" },
                "returncode": code,
                "stdout": out.stdout,
                "stderr": out.stderr
            })
        }
        Err(e) => json!({"status": "ERROR", "error": e.to_string()}),
    }
}

/// Emits the config-driven scene-build bpy script (used programmatically).
pub fn generate_scene_build_script(config_path: &str, out_script_path: &str) -> String {
    let abs_config = jsonfmt::dumps(&serde_json::json!(py::abspath(config_path)));
    let bpy_code = format!(
        r#"# Auto-generated by Autonomous 3D Studio
import bpy
import json
import os

with open({abs_config}, 'r') as f:
    config = json.load(f)

# Reset scene
bpy.ops.wm.read_factory_settings(use_empty=True)

# Process configuration
asset_name = config.get("asset_name", "SM_Asset")
print(f"[Blender Executor] Building asset: {{asset_name}}")

# Save .blend file
blend_out = config.get("export_blend", "asset.blend")
bpy.ops.wm.save_as_mainfile(filepath=blend_out)
print(f"[Blender Executor] Saved: {{blend_out}}")
"#,
        abs_config = abs_config
    );
    let _ = std::fs::write(out_script_path, bpy_code);
    out_script_path.to_string()
}

pub fn run(argv: &[String]) -> i32 {
    let args = cli::parse(
        "ciel-studio pipeline-exec",
        argv,
        &[
            ArgSpec::value("script", Some('s'), "script"),
            ArgSpec::flag("check", None, "check"),
        ],
    );

    let blender_bin = find_blender_binary();
    if args.flag("check") {
        match &blender_bin {
            Some(b) => {
                println!("Blender detected: {}", b);
                return 0;
            }
            None => {
                println!("Blender executable not found.");
                return 1;
            }
        }
    }
    if let Some(script) = args.get("script") {
        let result = execute_headless_blender_script(script, &[], 300);
        println!("{}", jsonfmt::dumps_indent(&result, 2));
    }
    0
}
