#!/usr/bin/env python3
"""
blender_pipeline_executor.py - Headless Blender Pipeline Master Execution Engine

Manages headless Blender (`blender -b -P`) batch pipelines, modifier stacks,
geometry cleanup, and multi-format asset export with structured JSON telemetry.
Hardened with process group management and SIGTERM/SIGKILL cleanup on timeouts.
"""

import sys
import os
import signal
import json
import shutil
import argparse
import subprocess

def find_blender_binary():
    """Locates Blender executable across standard OS paths."""
    bin_path = shutil.which("blender")
    if bin_path:
        return bin_path

    linux_paths = [
        "/usr/bin/blender",
        "/usr/local/bin/blender",
        "/opt/blender/blender",
        "/snap/bin/blender"
    ]
    for p in linux_paths:
        if os.path.exists(p) and os.access(p, os.X_OK):
            return p

    mac_path = "/Applications/Blender.app/Contents/MacOS/Blender"
    if os.path.exists(mac_path):
        return mac_path

    win_paths = [
        r"C:\Program Files\Blender Foundation\Blender 4.2\blender.exe",
        r"C:\Program Files\Blender Foundation\Blender 4.1\blender.exe",
        r"C:\Program Files\Blender Foundation\Blender 4.0\blender.exe",
        r"C:\Program Files\Blender Foundation\Blender 3.6\blender.exe"
    ]
    for p in win_paths:
        if os.path.exists(p):
            return p

    return None

def execute_headless_blender_script(script_path, extra_args=None, timeout_sec=300):
    """
    Runs a Python script inside Blender headless mode with process group management.
    """
    blender_bin = find_blender_binary()
    if not blender_bin:
        return {
            "status": "UNAVAILABLE",
            "error": "Blender executable not found on system. Generated scripts can still be run on client workstation.",
            "command": f"blender -b -P {script_path}"
        }

    cmd = [blender_bin, "-b", "--python", script_path]
    if extra_args:
        cmd.extend(["--"] + extra_args)

    print(f"[Blender Runner] Executing in new process group: {' '.join(cmd)}")
    proc = None
    try:
        # Use start_new_session=True so we can kill the entire process tree on timeout
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            start_new_session=True
        )
        stdout, stderr = proc.communicate(timeout=timeout_sec)
        return {
            "status": "SUCCESS" if proc.returncode == 0 else "ERROR",
            "returncode": proc.returncode,
            "stdout": stdout,
            "stderr": stderr
        }
    except subprocess.TimeoutExpired:
        if proc:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            except Exception:
                pass
        return {
            "status": "TIMEOUT",
            "error": f"Blender pipeline timed out after {timeout_sec} seconds and was cleanly terminated."
        }
    except Exception as e:
        if proc:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except Exception:
                pass
        return {
            "status": "ERROR",
            "error": str(e)
        }

def generate_scene_build_script(config_path, out_script_path):
    """
    Generates a bpy script from a JSON configuration with hardened string escaping.
    """
    abs_config = json.dumps(os.path.abspath(config_path))
    bpy_code = f"""# Auto-generated by Autonomous 3D Studio
import bpy
import json
import os

with open({abs_config}, 'r') as f:
    config = json.load(f)

# Reset scene
bpy.ops.wm.read_factory_settings(use_empty=True)

# Process configuration
asset_name = config.get("asset_name", "SM_Asset")
print(f"[Blender Executor] Building asset: {{asset_name}}")

# Save .blend file
blend_out = config.get("export_blend", "asset.blend")
bpy.ops.wm.save_as_mainfile(filepath=blend_out)
print(f"[Blender Executor] Saved: {{blend_out}}")
"""
    with open(out_script_path, 'w', encoding='utf-8') as f:
        f.write(bpy_code)
    return out_script_path

def main():
    parser = argparse.ArgumentParser(description="Autonomous 3D Studio Headless Blender Executor")
    parser.add_argument("--script", "-s", help="Path to Python script to execute inside Blender")
    parser.add_argument("--check", action="store_true", help="Check if Blender binary is available")

    args = parser.parse_args()

    blender_bin = find_blender_binary()
    if args.check:
        if blender_bin:
            print(f"Blender detected: {blender_bin}")
            sys.exit(0)
        else:
            print("Blender executable not found.")
            sys.exit(1)

    if args.script:
        result = execute_headless_blender_script(args.script)
        print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
